language: node_js
sudo: required
node_js:
  - 10.16.0
branches:
  only:
    - master
cache: yarn
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
script:
  - yarn
  - yarn install:plugin
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $access_token
  keep-history: true
  on:
    branch: master
  local-dir: _book